import Navbar from "@/components/nav/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body className="bg-zinc-900">
        <Navbar session={session} />
        <main className="min-h-screen pt-[60px]">{children}</main>
      </body>
    </html>
  );
}
